version: "3.8"

services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    restart: always
#  =====================================================================================================================
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    volumes:
      - ./core:/user/src/app
    environment:
      - DEBUG = True
    depends_on:
      - db
#  =====================================================================================================================

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

#  =====================================================================================================================
volumes:
  smtp4dev-data:
#  =====================================================================================================================