# Generated by Django 4.2 on 2025-07-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productmodels_brief_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodels',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
