# Generated by Django 4.2 on 2025-07-12 21:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_productmodels_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodels",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
