# Generated by Django 4.2 on 2025-07-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_wishlistmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodels',
            name='avg_rate',
            field=models.FloatField(default=0),
        ),
    ]
