# Generated by Django 4.2 on 2025-07-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
