# Generated by Django 4.2 on 2025-07-15 16:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_productmodels_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Coupon",
            new_name="CouponModels",
        ),
        migrations.RenameModel(
            old_name="OrderItem",
            new_name="OrderItemModels",
        ),
        migrations.RenameModel(
            old_name="Order",
            new_name="OrderModels",
        ),
    ]
