# Generated by Django 4.2 on 2025-07-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('order', '0004_ordermodels_final_price_ordermodels_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodels',
            name='payment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='payment.paymentmodels'),
        ),
        migrations.AlterField(
            model_name='couponmodels',
            name='max_usage_limit',
            field=models.PositiveIntegerField(),
        ),
    ]
