# Generated by Django 4.2 on 2025-07-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
        ("order", "0006_alter_ordermodels_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodels",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.paymentmodels",
            ),
        ),
    ]
