# Generated by Django 4.2 on 2025-07-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_productmodels_description"),
        ("order", "0011_ordermodels_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitemmodels",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_items",
                to="shop.productmodels",
            ),
        ),
    ]
